'use client';

import React, { useState } from 'react';
import { Play, ExternalLink } from 'lucide-react';
import { Youtube } from '@/components/icons/YouTubeIcon';
import { SITE_CONFIG } from '@/data/site-config';

interface YouTubeFacadeProps {
  videoId: string;
  title: string;
  aspectRatio?: 'video' | 'wide';
  className?: string;
  autoplayOnClick?: boolean;
  showSubscribeBadge?: boolean;
}

export function YouTubeFacade({
  videoId,
  title,
  className = '',
  autoplayOnClick = true,
  showSubscribeBadge = true,
}: YouTubeFacadeProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [imgError, setImgError] = useState(false);

  // Fallback to hqdefault if maxresdefault isn't generated by YouTube for this video
  const thumbUrl = imgError
    ? `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`
    : `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`;

  return (
    <div className={`relative overflow-hidden rounded-2xl bg-slate-900 shadow-xl border border-slate-800 ${className}`}>
      {isPlaying ? (
        <div className="relative w-full aspect-video">
          <iframe
            src={`https://www.youtube-nocookie.com/embed/${videoId}?autoplay=${autoplayOnClick ? 1 : 0}&rel=0&modestbranding=1`}
            title={title}
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowFullScreen
            className="absolute inset-0 w-full h-full border-0"
          />
        </div>
      ) : (
        <div
          onClick={() => setIsPlaying(true)}
          className="group relative w-full aspect-video cursor-pointer select-none overflow-hidden"
          role="button"
          tabIndex={0}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              setIsPlaying(true);
            }
          }}
          aria-label={`Lire la vidéo : ${title}`}
        >
          {/* Thumbnail */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={thumbUrl}
            alt={title}
            onError={() => setImgError(true)}
            className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
            loading="lazy"
          />

          {/* Dark gradient overlay for contrast */}
          <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-slate-950/20 to-transparent transition-opacity group-hover:opacity-90" />

          {/* Play Button - Apple-style centered badge */}
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="relative flex items-center justify-center w-16 h-16 sm:w-20 sm:h-20 rounded-full bg-red-600/90 text-white shadow-2xl backdrop-blur-md transition-all duration-300 group-hover:scale-110 group-hover:bg-red-600">
              <span className="absolute -inset-2 rounded-full bg-red-500/30 animate-ping opacity-60 pointer-events-none" />
              <Play className="w-7 h-7 sm:w-8 sm:h-8 fill-white translate-x-0.5" />
            </div>
          </div>

          {/* Video Title and Metadata at bottom */}
          <div className="absolute bottom-0 inset-x-0 p-4 sm:p-5 text-white">
            <div className="flex items-center gap-2 mb-1.5">
              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-500/20 text-red-300 border border-red-500/30 backdrop-blur-md">
                <Youtube className="w-3.5 h-3.5" />
                YouTube Vidéo
              </span>
              <span className="text-xs text-slate-300 font-medium">Prof. Omar Alami</span>
            </div>
            <h3 className="text-sm sm:text-base font-semibold line-clamp-2 text-white/95 group-hover:text-white transition-colors">
              {title}
            </h3>
          </div>
        </div>
      )}

      {/* Sub bar with direct YouTube subscription CTA */}
      {showSubscribeBadge && (
        <div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 bg-slate-950 border-t border-slate-800 text-xs sm:text-sm text-slate-300">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-500" />
            <span>Explication 100% gratuite</span>
          </div>
          <a
            href={SITE_CONFIG.youtube.channelUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 font-medium text-red-400 hover:text-red-300 hover:underline transition-colors"
          >
            S&apos;abonner sur YouTube
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>
      )}
    </div>
  );
}
